name: Survie
version: 0.1
author: HHugo_
main: fr.hhugo.survie.Survie
api-version: 1.21
commands:
  admin:
    description: Passe en mode administrateur
  gui:
    description: Configure le plugin depuis un menu
  customhoe:
    description: Recevoir la houe custom
  coins:
    description: Toutes les commandes liées aux coins