survie:

# Chemin vers la base de données
  database: "SurvieBDD.db"

# Permet de personnaliser les messages du chat
# Mettre %rank% pour avoir le rang du joueur
# Mettre %player% pour avoir le pseudo du joueur
# Mettre %message% pour avoir le message du joueur
  chat:
    format: "%rank%%player% &7» %message%"

# Permet de d'activer/désactiver le message de join/quit
  connexion_joueur:
    join: true
    quit: true

# Permet de personnaliser le GUI pour configurer le plugin en jeu
# Mettre %state% pour avoir l'état de la fonctionnalité (true/false)
  gui:
    name: "&8Configuration du plugin"
    join_message_item:
      material: GREEN_DYE
      name: "&7Message de &3JOIN"
      lore:
        - "&8Clique pour activer/désactiver le message de join"
        - "&8Etat : &6%state%"
    quit_message_item:
      material: RED_DYE
      name: "&7Message de &3QUIT"
      lore:
        - "&8Clique pour activer/désactiver le message de quit"
        - "&8Etat : &6%state%"

# Permet de personnalier le GUI du profil du joueur
  gui_joueur:
    name: "&8Profil de &6%player%"

# Permet de personnaliser la houe de plantations
# Mettre %amount% pour avoir le montant d'utilisations
  agriculture:
    houe_plantations:
      name: "&6Super Houe"
      lore:
        - "&8Permet de planter sur 3x3 blocs"